package com.vcs.database.scrollable;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class MyAutoGeneratedKeys {

	   public static void main(String a[]){
	         
	        Connection con = null;
	        PreparedStatement pstmt = null;
	        ResultSet rs = null;
	        try {
	            Class.forName("oracle.jdbc.driver.OracleDriver");
	            con = DriverManager.
	                getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","student");
	            String query = "insert into employee (empid,empname) values (?.?)";
	            pstmt = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
	            pstmt.setInt(1, 1);
	            pstmt.setString(2, "John");
	            pstmt.executeUpdate();
	            rs = pstmt.getGeneratedKeys();
	            if(rs != null && rs.next()){
	                System.out.println("Generated Emp Id: "+rs.getInt(1));
	            }
	 
	        } catch (ClassNotFoundException e) {
	            e.printStackTrace();
	        } catch (SQLException e) {
	            e.printStackTrace();
	        } finally{
	            try{
	                if(rs != null) rs.close();
	                if(pstmt != null) pstmt.close();
	                if(con != null) con.close();
	            } catch(Exception ex){}
	        }
	    }
	//- See more at: http://www.java2novice.com/jdbc/auto-generated-keys/#sthash.lgtGIRKZ.dpuf
}
